export const ANSWER_LIST_REQUEST = "ANSWER_LIST_REQUEST";
export const ANSWER_LIST_SUCCESS = "ANSWER_LIST_SUCCESS";
export const ANSWER_LIST_FAILURE = "ANSWER_LIST_FAILURE";

export const DELETE_ANSWER_REQUEST = "DELETE_ANSWER_REQUEST";
export const DELETE_ANSWER_SUCCESS = "DELETE_ANSWER_SUCCESS";
export const DELETE_ANSWER_FAIL = "DELETE_ANSWER_FAIL";


