export const GET_ANSWER_REQUEST = "GET_ANSWER_REQUEST";
export const GET_ANSWER_SUCCESS = "GET_ANSWER_SUCCESS";
export const GET_ANSWER_FAIL = "GET_ANSWER_FAIL";

export const EDIT_ANSWER_REQUEST = "EDIT_ANSWER_REQUEST";
export const EDIT_ANSWER_SUCCESS = "EDIT_ANSWER_SUCCESS";
export const EDIT_ANSWER_FAIL = "EDIT_ANSWER_FAIL";