export const USER_ANSWER_LIST_REQUEST = "USER_ANSWER_LIST_REQUEST";
export const USER_ANSWER_LIST_SUCCESS = "USER_ANSWER_LIST_SUCCESS";
export const USER_ANSWER_LIST_FAILURE = "USER_ANSWER_LIST_FAILURE";

export const USER_DELETE_ANSWER_REQUEST = "USER_DELETE_ANSWER_REQUEST";
export const USER_DELETE_ANSWER_SUCCESS = "USER_DELETE_ANSWER_SUCCESS";
export const USER_DELETE_ANSWER_FAIL = "USER_DELETE_ANSWER_FAIL";