export const SEARCH_LIST_REQUEST = "SEARCH_LIST_REQUEST";
export const SEARCH_LIST_SUCCESS = "SEARCH_LIST_SUCCESS";
export const SEARCH_LIST_FAILURE = "SEARCH_LIST_FAILURE";

export const CLEAR_SEARCH_LIST = "CLEAR_SEARCH_LIST";