export const QUESTION_VOTE = "QUESTION_VOTE";
export const ANSWER_VOTE = "ANSWER_VOTE";
export const SEARCH_VOTE = "SEARCH_VOTE";
export const USER_POST_VOTE = "USER_POST_VOTE";
export const USER_ANSWER_VOTE = "USER_ANSWER_VOTE";

