# Generated by Django 4.0 on 2022-01-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListedPasswordResetTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
            ],
        ),
    ]
